name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # svakih 10 minuta
  workflow_dispatch:         # manuelni trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://motomanagerru.onrender.com/)
          echo "Response status: $STATUS"
